// Generated by CoffeeScript 1.6.3
(function() {
    module.exports = function(robot) {
        return robot.respond(
            /hello/i,
            function(res) {
                return res.send("world");});
    };
}).call(this);

