// Generated by CoffeeScript 1.6.3
(function() {
    module.exports = function(robot) {
        return robot.respond(
            /hello/i,
            function(res) {
                return res.send("world");});
    };
}).call(this);


(function() {
    module.exports = function(robot) {

        // hello world
        robot.hear(/helo/i, (res) => {
            res.send("world");
        });

        // sushi
        robot.hear(/sushi/i, (res) => {
            res.send(":sushi: SUSHIRO↑ SUSHIRO↓");
        });
    };
}).call(this);

